{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "UTC\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-40:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-41:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "Exception in thread Thread-42:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-43:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "Exception in thread Thread-44:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "Exception in thread Thread-45:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "Exception in thread Thread-46:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "Exception in thread Thread-47:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "        end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "Exception in thread Thread-49:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "Exception in thread Thread-50:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "Exception in thread Thread-48:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "Exception in thread Thread-51:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 171, in history\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    dt = _tz.timezone(exchange_tz).localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'nan'\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [4], line 11\u001b[0m\n\u001b[1;32m      9\u001b[0m end_date \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39m2021-10-31\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m     10\u001b[0m time_interval\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m1D\u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m---> 11\u001b[0m temp_df \u001b[39m=\u001b[39m yf\u001b[39m.\u001b[39;49mdownload(tic, start\u001b[39m=\u001b[39;49mstart_date, end\u001b[39m=\u001b[39;49mend_date, interval\u001b[39m=\u001b[39;49mtime_interval,proxy\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39m127.0.0.1:10809\u001b[39;49m\u001b[39m'\u001b[39;49m)  \n\u001b[1;32m     12\u001b[0m \u001b[39mprint\u001b[39m(temp_df)\n",
      "File \u001b[0;32m~/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py:118\u001b[0m, in \u001b[0;36mdownload\u001b[0;34m(tickers, start, end, actions, threads, ignore_tz, group_by, auto_adjust, back_adjust, keepna, progress, period, show_errors, interval, prepost, proxy, rounding, timeout, **kwargs)\u001b[0m\n\u001b[1;32m    111\u001b[0m         _download_one_threaded(ticker, period\u001b[39m=\u001b[39mperiod, interval\u001b[39m=\u001b[39minterval,\n\u001b[1;32m    112\u001b[0m                                start\u001b[39m=\u001b[39mstart, end\u001b[39m=\u001b[39mend, prepost\u001b[39m=\u001b[39mprepost,\n\u001b[1;32m    113\u001b[0m                                actions\u001b[39m=\u001b[39mactions, auto_adjust\u001b[39m=\u001b[39mauto_adjust,\n\u001b[1;32m    114\u001b[0m                                back_adjust\u001b[39m=\u001b[39mback_adjust, keepna\u001b[39m=\u001b[39mkeepna,\n\u001b[1;32m    115\u001b[0m                                progress\u001b[39m=\u001b[39m(progress \u001b[39mand\u001b[39;00m i \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m), proxy\u001b[39m=\u001b[39mproxy,\n\u001b[1;32m    116\u001b[0m                                rounding\u001b[39m=\u001b[39mrounding, timeout\u001b[39m=\u001b[39mtimeout)\n\u001b[1;32m    117\u001b[0m     \u001b[39mwhile\u001b[39;00m \u001b[39mlen\u001b[39m(shared\u001b[39m.\u001b[39m_DFS) \u001b[39m<\u001b[39m \u001b[39mlen\u001b[39m(tickers):\n\u001b[0;32m--> 118\u001b[0m         _time\u001b[39m.\u001b[39;49msleep(\u001b[39m0.01\u001b[39;49m)\n\u001b[1;32m    120\u001b[0m \u001b[39m# download synchronously\u001b[39;00m\n\u001b[1;32m    121\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    122\u001b[0m     \u001b[39mfor\u001b[39;00m i, ticker \u001b[39min\u001b[39;00m \u001b[39menumerate\u001b[39m(tickers):\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import yfinance as yf\n",
    "import pytz\n",
    "from tzlocal import get_localzone\n",
    "# tz = pytz.timezone.utc\n",
    "local = pytz.timezone('UTC')\n",
    "print(local)\n",
    "tic = ['AXP', 'AMGN', 'AAPL', 'BA', 'CAT', 'CSCO', 'CVX', 'GS', 'HD', 'HON', 'IBM', 'INTC']\n",
    "start_date = '2008-01-01'\n",
    "end_date = '2021-10-31'\n",
    "time_interval='1D'\n",
    "temp_df = yf.download(tic, start=start_date, end=end_date, interval=time_interval,proxy='127.0.0.1:10809')  \n",
    "print(temp_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Asia/Shanghai\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-28:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Exception in thread Thread-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-30:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-31:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "Exception in thread Thread-32:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-33:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-34:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "Exception in thread Thread-35:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "Exception in thread Thread-36:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "Exception in thread Thread-37:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "Exception in thread Thread-38:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "Exception in thread Thread-39:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    self.run()\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/threading.py\", line 870, in run\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "        data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/multitasking/__init__.py\", line 104, in _run_via_pool\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    return callee(*args, **kwargs)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 199, in _download_one_threaded\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    data = _download_one(ticker, start, end, auto_adjust, back_adjust,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/multi.py\", line 213, in _download_one\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    return Ticker(ticker).history(period=period, interval=interval,\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/base.py\", line 170, in history\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    end = utils._parse_user_dt(end, tz)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/yfinance/utils.py\", line 157, in _parse_user_dt\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "        dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "dt = _tz.timezone('Asia/Shanghai').localize(dt)\n",
      "  File \"/home/cheers/anaconda3/envs/finrl/lib/python3.8/site-packages/pytz/__init__.py\", line 189, in timezone\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n",
      "    raise UnknownTimeZoneError(zone)\n",
      "pytz.exceptions.UnknownTimeZoneError: 'Asia/Shangri-La'\n"
     ]
    }
   ],
   "source": [
    "import yfinance as yf\n",
    "import pytz\n",
    "# from tzlocal import get_localzone\n",
    "# local = pytz.timezone('utc')\n",
    "from tzlocal import get_localzone\n",
    "local = pytz.timezone(str(get_localzone()))\n",
    "print(local)\n",
    "from datetime import datetime as datetime\n",
    "tic = ['AXP', 'AMGN', 'AAPL', 'BA', 'CAT', 'CSCO', 'CVX', 'GS', 'HD', 'HON', 'IBM', 'INTC']\n",
    "start_date  = datetime (2008,1,1)\n",
    "end_date   = datetime (2008,10,30)\n",
    "# start_date = '2008-01-01'\n",
    "# end_date = '2008-10-31'\n",
    "time_interval='1D'\n",
    "temp_df = yf.download(tic, start=start_date, end=end_date, interval=time_interval,proxy='127.0.0.1:10809')  \n",
    "print(temp_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.5 ('finrl')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "4a5901315a0f4e97c6f68c05146f6b2bc52d5562d6c8a28548099e61bf237d61"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
